spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: password
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

