spring:
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/blog_engine?useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: password
    initialization-mode: always
#  session.store-type: redis
#  session:
#    redis.namespace: spring:session
#  redis:
#    port: 6379
#    host: localhost
#    password: password

server:
  servlet:
    session.timeout: 1
logging:
  level:
    web: DEBUG

log4j:
  appender:
    stdout:
      Target=: log/log.txt