spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${DB_URL}
    username: root
    password: password
    initialization-mode: never
  mail:
    host: smtp.yandex.ru
    username: ${EMAIL}
    password: ${PASSWORD}
    port: 465
    protocol: smtps

  servlet:
    multipart:
      max-file-size: 5MB
      enabled: false


#========================= App variables ============================

restore_code:
  code_length: 40
  expiration_time: 60
captcha:
  expiration:
    time: 10
  text_size: 15
  frame_width: 100
  frame_height: 40
  width: 40
  height: 20
  secret_length: 15
  code_length: 4
password:
  min_length: 6

settings: "{
  MULTIUSER_MODE: 'Многопользовательский режим',
  POST_PREMODERATION: 'Премодерация постов',
  STATISTICS_IS_PUBLIC: 'Показывать всем статистику блога'
}"

setting:
  multiuser: MULTIUSER_MODE

blog_info:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 903 666-44-55"
  email: "mail@mail.ru"
  copyright: "Дмитрий Сергеев"
  copyright_form: "2005"

image:
  crop_height: 36
  crop_width: 36
  max_size: 5242880

location:
  avatars: "avatars/"
  images: "images/"

tag:
  min_weight: 0.1













#errormessages:
#  captcha: 'Код с картинки введён неверно'
#  name: 'Имя указано неверно'
#  user:
#    notfound: 'Не найден пользователь с таким адресом почты'
#    exists: 'Этот e-mail уже зарегистрирован'